#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def fibonacci(n):
    """Function returns the Fibonacci sequence with max value of n as an ordered list of ints"""
    a,b = 1,2
    seq = []
    while a < n:
        seq.append(a)
        a,b, = b,a+b

    return seq

l = fibonacci(4000000)

evens = [x for x in l if x%2 == 0]

print sum(evens)
